name: Test
on: 
  pull_request_target:
    branches: [main]
permissions:
  id-token: write
  contents: read
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
        with:
          # For `pull_request_target`, we want to pull the PR and not the target branch
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          persist-credentials: false
      - name: Setup Node.js 14.x
        uses: actions/setup-node@main
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: yarn
      - name: Run Spellcheck
        run: yarn spellcheck
      - name: Fetch Amplify backend configuration
        uses: ./.github/actions/fetch_amplify_backend
        with:
          role-to-assume: ${{ secrets.AWS_ARN_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          app-id: ${{ secrets.APP_ID }}
      - name: Run tests
        run: yarn test
      - name: Run Build
        run: yarn build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
